### ISSUE TITLE
Security issue

### ISSUE THREAD

**Issue by suculent** [philhawthorne/docker-influxdb-grafana#6]
Hi, why does the image permit root login with password? I’ve just noticed that after two attacks. It’s not needed by docker.

**Comment by diogopms** [comment]
Should be fixed: #13

**Comment by philhawthorne** [comment]
This is fixed on the `dev` branch now thanks to @diogopms 

You can use this version by running the `edge` tag in Docker, until this is released to the main branch. Once thats done I'll close this issue.

**Comment by zerog2k** [comment]
Thanks philhawthorne for the great docker image. Also glad to see ssh getting (mostly) removed from this, but I still see openssh-server getting installed in dockerfile:
https://github.com/philhawthorne/docker-influxdb-grafana/blob/dev/Dockerfile#L34
Any ideas on when it would get tagged to `latest`?

**Comment by philhawthorne** [comment]
@zerog2k great pickup!

I'll remove that in the dev branch now

**Comment by philhawthorne** [comment]
Fixed in #23
